### ISSUE TITLE
Estilo de la pantalla de pago

### ISSUE THREAD

**Issue by jforni** [RodrigosalvatierraDev/eCommerceGMS#1]
Todas las páginas del proyecto deberían tener el mismo formato y estilo, en la pantalla de pago faltan el header y el footer, lo que la hace vacía y sin opciones para el usuario.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/d514b279-69a8-4d33-b1fc-1c4bc2ab9be8)

**Comment by RodrigosalvatierraDev** [comment]
Corregido
