### ISSUE TITLE
Enlaces a sitios externos

### ISSUE THREAD

**Issue by jforni** [RodrigosalvatierraDev/eCommerceGMS#2]
Los enlaces a sitios externos, como redes sociales, repositorio, etc, deberían abrirse en pestañas independientes a la página del proyecto, para no perder al usuario.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/a2a88bbd-5925-4073-b673-5dcd5b500516)

**Comment by RodrigosalvatierraDev** [comment]
Listo ya lo modifique
