### ISSUE TITLE
ARtículos favoritos

### ISSUE THREAD

**Issue by jforni** [RodrigosalvatierraDev/eCommerceGMS#3]
Si un usuario registrado selecciona productos favoritos, solo a ese usuario se le deben mostrar.
Con mi cuenta selecciono productos como favoritos, y cuando salgo de la cuenta, me los sigue mostrando en la página de favoritos sin estar logueado.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/acf12f27-239b-4ddb-8f5b-b880b2264043)

**Comment by RodrigosalvatierraDev** [comment]
Listo, lo que hize fue que verifique si esta loggeado o no, si no esta se muestra un cartel que se logge para ver los favoritos y una vez loggeado se puede ver los favoritos que estas seleccionando.
